name: Build and Release Astra CLI

on:
  push:
    tags:
      - 'astra-cli-*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        cd integrations/astra-cli
        ext=""
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          ext=".exe"
        fi
        go build -o astra-cli-${{ matrix.os }}-${{ matrix.arch }}${ext}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: astra-cli-${{ matrix.os }}-${{ matrix.arch }}${ext}
        path: integrations/astra-cli/astra-cli-${{ matrix.os }}-${{ matrix.arch }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v3
      with:
        path: binaries/

    - name: Verify Artifacts
      run: ls  binaries

    - name: Create Version Release
      uses: softprops/action-gh-release@v1
      with:
        files: binaries/**/*
        tag_name: ${{ github.ref_name }}  # Clean tag name
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        repository: dharrsan-18/astra-cli-artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

