name: Build and Release Astra CLI

on:
  push:
    tags:
      - 'astra-cli-*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""
          - os: linux
            arch: arm64
            ext: ""
          - os: windows
            arch: amd64
            ext: ".exe"
          - os: windows
            arch: arm64
            ext: ".exe"
          - os: darwin
            arch: amd64
            ext: ""
          - os: darwin
            arch: arm64
            ext: ""
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        cd integrations/astra-cli
        go build -o astra-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: integrations/astra-cli/astra-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: binaries

    - name: Clone Public Release Repository
      run: |
        git clone https://github.com/dharrsan-18/astra-cli-artifacts.git public-repo
        cd public-repo
        git checkout main

    - name: Copy Artifacts to Public Repo
      run: |
        cp binaries/* public-repo/
        cd public-repo
        git add .
        git commit -m "Release ${{ github.ref_name }}"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}