name: Build and Release Astra CLI

on:
  push:
    tags:
      - 'astra-cli-*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: amd64
            ext: ""
            build_tags: ""
          - os: linux
            arch: arm64
            ext: ""
            build_tags: ""
          - os: windows
            arch: amd64
            ext: ".exe"
            build_tags: "windows"  # Add windows build tag
            build_flags: "-tags windows"
          - os: windows
            arch: arm64
            ext: ".exe"
            build_tags: "windows"  # Add windows build tag
            build_flags: "-tags windows"
          - os: darwin
            arch: amd64
            ext: ""
            build_tags: ""
          - os: darwin
            arch: arm64
            ext: ""
            build_tags: ""

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    # Create temporary file with build constraints for Windows
    - name: Setup Windows Build
      if: matrix.os == 'windows'
      run: |
        echo '//go:build windows
        // +build windows
        
        package main
        
        import "syscall"
        
        var (
            syscallFlock = func(fd int, how int) (err error) { return nil }
            LOCK_EX = 0
            LOCK_NB = 0
            LOCK_UN = 0
        )' > integrations/astra-cli/syscall_windows.go

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        cd integrations/astra-cli
        go build ${{ matrix.build_flags }} -o astra-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: integrations/astra-cli/astra-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: binaries

    - name: Create Version Release
      uses: softprops/action-gh-release@v1
      with:
        files: binaries/*
        tag_name: ${{ github.ref }}
        name: Astra CLI ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Latest Release
      uses: softprops/action-gh-release@v1
      with:
        files: binaries/*
        tag_name: latest
        name: Latest Astra CLI Release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}